---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ycsb-load
  labels:
    group: nuodb
spec:
  replicas: 1
  selector:
    app: ycsb-load
  template:
    metadata:
      name: ycsb-load
      labels:
        app: ycsb-load
        database: hockeydb01
    spec:
      containers:
      - name: ycsb-load
        image: nuodb/ycsb:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ycsbpod
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: nuodb 
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - { name: PEER_ADDRESS,        value: "10.36.0.4" }
        - { name: DB_NAME,             value: "hockeydb01" }
        - { name: DB_USER,             value: "dba" }  
        - { name: DB_PASSWORD,         value: "secret" }  

